version: '2'


services:

  geoserver:
    image: camptocamp/geonode_geoserver
    build: .
    links:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      - geoserver_datadir:/usr/local/tomcat/webapps/geoserver/data

  postgis:
    image: kartoza/postgis
    ports:
      - "54322:5432"
    volumes:
      - postgis_data:/var/lib/postgresql


volumes:
  # reference to the named data container that holds the preloaded geoserver data directory 
  geoserver_datadir:
  postgis_data:
